Fixup: Handle non-existence of pre/postscript directory
Commit 393e566a660f6ee8b3235466768f2f919416db98 introduces pre/postscript plugin support, assumed the pre/postscript directory to be present always in the config directory, which is not the case and that is a user created directory, need not be present in environment on a fresh clone, hence user will observe a below failure during bootstrap

00:10:33 INFO    : Cloning the repo: avocado-misc-tests in /home/kvmci/tests/tests/avocado-misc-tests
Traceback (most recent call last):
  File "avocado-setup.py", line 667, in <module>
    bootstrap(args.enable_kvm)
  File "avocado-setup.py", line 341, in bootstrap
    if len(os.listdir(prescript)):
FileNotFoundError: [Errno 2] No such file or directory: '/home/kvmci/tests/config/prescript'

So, Let's handle such cases.

Reported-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>
Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>