NIC: inputfile create fails due to hard link issue
while creating inputfile for network devices the script
fails at get_interfaces_in_pci_address() to fetch pci
interface name with below error

  File "/root/tests/lib/pci.py", line 331, in <listcomp>
    if pci_address in os.readlink(os.path.join(pci_class_path,
OSError: [Errno 22] Invalid argument: '/sys/class/net/bonding_masters'

This patch make sures the hardlinks are ignored and only
the symlinks are checked for pci address

Signed-off-by: Abdul Haleem <abdhalee@linux.vnet.ibm.com>